### ISSUE TITLE
doesn't work on search page

### ISSUE THREAD

**Issue by Zmey25** [doguh/yt-no-translate#1]
Hi, i'm from mozilla review site. I'm not a dev and doesn't know how to help you with this problem, but at search result page on youtube i'm still can see auto-translated titles.
For example, url is here: https://www.youtube.com/results?search_query=
Specific video is here, but it translate titles only on search result page: https://www.youtube.com/watch?v=x9ElqeMxy9U

If you need more info, just let me know

**Comment by doguh** [comment]
Hello, thank you for the feedback!

Yes currently the addon only prevent translation for the video title under the actual video.

It does not work on other pages (like home page or search results) and for videos in the recommendations column. I'm not sure if it's doable I didn't try yet.

**Comment by D3m3rion** [comment]
Hey there!
It would be great if you could give it a try because feeds (like subs or home) are the most annoying places for the automatic translation. If it's an English title, I'm more likely to click on the video, but when the video itself is not in English, I just wasted my time :)
